package model

// !!! DO NOT EDIT THIS FILE

import (
	"context"
	"encoding/json"
	"github.com/iancoleman/strcase"
	"github.com/mylxsw/coll"
	"github.com/mylxsw/eloquent/query"
	"gopkg.in/guregu/null.v3"
	"time"
)

func init() {

}

// Attachment is a Attachment object
type Attachment struct {
	original        *attachmentOriginal
	attachmentModel *AttachmentModel

	Id        null.Int
	ShareId   null.Int
	Name      null.String
	AttaType  null.String
	AttaPath  null.String
	CreatedAt null.Time
}

// As convert object to other type
// dst must be a pointer to struct
func (inst *Attachment) As(dst interface{}) error {
	return coll.CopyProperties(inst, dst)
}

// SetModel set model for Attachment
func (inst *Attachment) SetModel(attachmentModel *AttachmentModel) {
	inst.attachmentModel = attachmentModel
}

// attachmentOriginal is an object which stores original Attachment from database
type attachmentOriginal struct {
	Id        null.Int
	ShareId   null.Int
	Name      null.String
	AttaType  null.String
	AttaPath  null.String
	CreatedAt null.Time
}

// Staled identify whether the object has been modified
func (inst *Attachment) Staled(onlyFields ...string) bool {
	if inst.original == nil {
		inst.original = &attachmentOriginal{}
	}

	if len(onlyFields) == 0 {

		if inst.Id != inst.original.Id {
			return true
		}
		if inst.ShareId != inst.original.ShareId {
			return true
		}
		if inst.Name != inst.original.Name {
			return true
		}
		if inst.AttaType != inst.original.AttaType {
			return true
		}
		if inst.AttaPath != inst.original.AttaPath {
			return true
		}
		if inst.CreatedAt != inst.original.CreatedAt {
			return true
		}
	} else {
		for _, f := range onlyFields {
			switch strcase.ToSnake(f) {

			case "id":
				if inst.Id != inst.original.Id {
					return true
				}
			case "share_id":
				if inst.ShareId != inst.original.ShareId {
					return true
				}
			case "name":
				if inst.Name != inst.original.Name {
					return true
				}
			case "atta_type":
				if inst.AttaType != inst.original.AttaType {
					return true
				}
			case "atta_path":
				if inst.AttaPath != inst.original.AttaPath {
					return true
				}
			case "created_at":
				if inst.CreatedAt != inst.original.CreatedAt {
					return true
				}
			default:
			}
		}
	}

	return false
}

// StaledKV return all fields has been modified
func (inst *Attachment) StaledKV(onlyFields ...string) query.KV {
	kv := make(query.KV, 0)

	if inst.original == nil {
		inst.original = &attachmentOriginal{}
	}

	if len(onlyFields) == 0 {

		if inst.Id != inst.original.Id {
			kv["id"] = inst.Id
		}
		if inst.ShareId != inst.original.ShareId {
			kv["share_id"] = inst.ShareId
		}
		if inst.Name != inst.original.Name {
			kv["name"] = inst.Name
		}
		if inst.AttaType != inst.original.AttaType {
			kv["atta_type"] = inst.AttaType
		}
		if inst.AttaPath != inst.original.AttaPath {
			kv["atta_path"] = inst.AttaPath
		}
		if inst.CreatedAt != inst.original.CreatedAt {
			kv["created_at"] = inst.CreatedAt
		}
	} else {
		for _, f := range onlyFields {
			switch strcase.ToSnake(f) {

			case "id":
				if inst.Id != inst.original.Id {
					kv["id"] = inst.Id
				}
			case "share_id":
				if inst.ShareId != inst.original.ShareId {
					kv["share_id"] = inst.ShareId
				}
			case "name":
				if inst.Name != inst.original.Name {
					kv["name"] = inst.Name
				}
			case "atta_type":
				if inst.AttaType != inst.original.AttaType {
					kv["atta_type"] = inst.AttaType
				}
			case "atta_path":
				if inst.AttaPath != inst.original.AttaPath {
					kv["atta_path"] = inst.AttaPath
				}
			case "created_at":
				if inst.CreatedAt != inst.original.CreatedAt {
					kv["created_at"] = inst.CreatedAt
				}
			default:
			}
		}
	}

	return kv
}

// Save create a new model or update it
func (inst *Attachment) Save(onlyFields ...string) error {
	if inst.attachmentModel == nil {
		return query.ErrModelNotSet
	}

	id, _, err := inst.attachmentModel.SaveOrUpdate(*inst, onlyFields...)
	if err != nil {
		return err
	}

	inst.Id = null.IntFrom(id)
	return nil
}

// Delete remove a attachment
func (inst *Attachment) Delete() error {
	if inst.attachmentModel == nil {
		return query.ErrModelNotSet
	}

	_, err := inst.attachmentModel.DeleteById(inst.Id.Int64)
	if err != nil {
		return err
	}

	return nil
}

// String convert instance to json string
func (inst *Attachment) String() string {
	rs, _ := json.Marshal(inst)
	return string(rs)
}

func (inst *Attachment) Share() *AttachmentBelongsToShareRel {
	return &AttachmentBelongsToShareRel{
		source:   inst,
		relModel: NewShareModel(inst.attachmentModel.GetDB()),
	}
}

type AttachmentBelongsToShareRel struct {
	source   *Attachment
	relModel *ShareModel
}

func (rel *AttachmentBelongsToShareRel) Create(target Share) (int64, error) {
	targetId, err := rel.relModel.Save(target)
	if err != nil {
		return 0, err
	}

	target.Id = null.IntFrom(targetId)

	rel.source.ShareId = target.Id
	if err := rel.source.Save(); err != nil {
		return targetId, err
	}

	return targetId, nil
}

func (rel *AttachmentBelongsToShareRel) Exists(builders ...query.SQLBuilder) (bool, error) {
	builder := query.Builder().Where("id", rel.source.ShareId).Merge(builders...)

	return rel.relModel.Exists(builder)
}

func (rel *AttachmentBelongsToShareRel) First(builders ...query.SQLBuilder) (Share, error) {
	builder := query.Builder().Where("id", rel.source.ShareId).Limit(1).Merge(builders...)

	return rel.relModel.First(builder)
}

func (rel *AttachmentBelongsToShareRel) Associate(target Share) error {
	rel.source.ShareId = target.Id
	return rel.source.Save()
}

func (rel *AttachmentBelongsToShareRel) Dissociate() error {
	rel.source.ShareId = null.IntFrom(0)
	return rel.source.Save()
}

type attachmentScope struct {
	name  string
	apply func(builder query.Condition)
}

var attachmentGlobalScopes = make([]attachmentScope, 0)
var attachmentLocalScopes = make([]attachmentScope, 0)

// AddGlobalScopeForAttachment assign a global scope to a model
func AddGlobalScopeForAttachment(name string, apply func(builder query.Condition)) {
	attachmentGlobalScopes = append(attachmentGlobalScopes, attachmentScope{name: name, apply: apply})
}

// AddLocalScopeForAttachment assign a local scope to a model
func AddLocalScopeForAttachment(name string, apply func(builder query.Condition)) {
	attachmentLocalScopes = append(attachmentLocalScopes, attachmentScope{name: name, apply: apply})
}

func (m *AttachmentModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range attachmentGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range attachmentLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *AttachmentModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *AttachmentModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

type AttachmentPlain struct {
	Id        int64
	ShareId   int64
	Name      string
	AttaType  string
	AttaPath  string
	CreatedAt time.Time
}

func (w AttachmentPlain) ToAttachment(allows ...string) Attachment {
	if len(allows) == 0 {
		return Attachment{

			Id:        null.IntFrom(int64(w.Id)),
			ShareId:   null.IntFrom(int64(w.ShareId)),
			Name:      null.StringFrom(w.Name),
			AttaType:  null.StringFrom(w.AttaType),
			AttaPath:  null.StringFrom(w.AttaPath),
			CreatedAt: null.TimeFrom(w.CreatedAt),
		}
	}

	res := Attachment{}
	for _, al := range allows {
		switch strcase.ToSnake(al) {

		case "id":
			res.Id = null.IntFrom(int64(w.Id))
		case "share_id":
			res.ShareId = null.IntFrom(int64(w.ShareId))
		case "name":
			res.Name = null.StringFrom(w.Name)
		case "atta_type":
			res.AttaType = null.StringFrom(w.AttaType)
		case "atta_path":
			res.AttaPath = null.StringFrom(w.AttaPath)
		case "created_at":
			res.CreatedAt = null.TimeFrom(w.CreatedAt)
		default:
		}
	}

	return res
}

// As convert object to other type
// dst must be a pointer to struct
func (w AttachmentPlain) As(dst interface{}) error {
	return coll.CopyProperties(w, dst)
}

func (w *Attachment) ToAttachmentPlain() AttachmentPlain {
	return AttachmentPlain{

		Id:        w.Id.Int64,
		ShareId:   w.ShareId.Int64,
		Name:      w.Name.String,
		AttaType:  w.AttaType.String,
		AttaPath:  w.AttaPath.String,
		CreatedAt: w.CreatedAt.Time,
	}
}

// AttachmentModel is a model which encapsulates the operations of the object
type AttachmentModel struct {
	db        *query.DatabaseWrap
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string

	query query.SQLBuilder
}

var attachmentTableName = "attachment"

const (
	AttachmentFieldId        = "id"
	AttachmentFieldShareId   = "share_id"
	AttachmentFieldName      = "name"
	AttachmentFieldAttaType  = "atta_type"
	AttachmentFieldAttaPath  = "atta_path"
	AttachmentFieldCreatedAt = "created_at"
)

// AttachmentFields return all fields in Attachment model
func AttachmentFields() []string {
	return []string{
		"id",
		"share_id",
		"name",
		"atta_type",
		"atta_path",
		"created_at",
	}
}

func SetAttachmentTable(tableName string) {
	attachmentTableName = tableName
}

// NewAttachmentModel create a AttachmentModel
func NewAttachmentModel(db query.Database) *AttachmentModel {
	return &AttachmentModel{
		db:                  query.NewDatabaseWrap(db),
		tableName:           attachmentTableName,
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
		query:               query.Builder(),
	}
}

// GetDB return database instance
func (m *AttachmentModel) GetDB() query.Database {
	return m.db.GetDB()
}

func (m *AttachmentModel) clone() *AttachmentModel {
	return &AttachmentModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
		query:               m.query,
	}
}

// WithoutGlobalScopes remove a global scope for given query
func (m *AttachmentModel) WithoutGlobalScopes(names ...string) *AttachmentModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

// WithLocalScopes add a local scope for given query
func (m *AttachmentModel) WithLocalScopes(names ...string) *AttachmentModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

// Condition add query builder to model
func (m *AttachmentModel) Condition(builder query.SQLBuilder) *AttachmentModel {
	mm := m.clone()
	mm.query = mm.query.Merge(builder)

	return mm
}

// Find retrieve a model by its primary key
func (m *AttachmentModel) Find(id int64) (Attachment, error) {
	return m.First(m.query.Where("id", "=", id))
}

// Exists return whether the records exists for a given query
func (m *AttachmentModel) Exists(builders ...query.SQLBuilder) (bool, error) {
	count, err := m.Count(builders...)
	return count > 0, err
}

// Count return model count for a given query
func (m *AttachmentModel) Count(builders ...query.SQLBuilder) (int64, error) {
	sqlStr, params := m.query.
		Merge(builders...).
		Table(m.tableName).
		AppendCondition(m.applyScope()).
		ResolveCount()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	defer rows.Close()

	rows.Next()
	var res int64
	if err := rows.Scan(&res); err != nil {
		return 0, err
	}

	return res, nil
}

func (m *AttachmentModel) Paginate(page int64, perPage int64, builders ...query.SQLBuilder) ([]Attachment, query.PaginateMeta, error) {
	if page <= 0 {
		page = 1
	}

	if perPage <= 0 {
		perPage = 15
	}

	meta := query.PaginateMeta{
		PerPage: perPage,
		Page:    page,
	}

	count, err := m.Count(builders...)
	if err != nil {
		return nil, meta, err
	}

	meta.Total = count
	meta.LastPage = count / perPage
	if count%perPage != 0 {
		meta.LastPage += 1
	}

	res, err := m.Get(append([]query.SQLBuilder{query.Builder().Limit(perPage).Offset((page - 1) * perPage)}, builders...)...)
	if err != nil {
		return res, meta, err
	}

	return res, meta, nil
}

// Get retrieve all results for given query
func (m *AttachmentModel) Get(builders ...query.SQLBuilder) ([]Attachment, error) {
	b := m.query.Merge(builders...).Table(m.tableName).AppendCondition(m.applyScope())
	if len(b.GetFields()) == 0 {
		b = b.Select(
			"id",
			"share_id",
			"name",
			"atta_type",
			"atta_path",
			"created_at",
		)
	}

	fields := b.GetFields()
	selectFields := make([]query.Expr, 0)

	for _, f := range fields {
		switch strcase.ToSnake(f.Value) {

		case "id":
			selectFields = append(selectFields, f)
		case "share_id":
			selectFields = append(selectFields, f)
		case "name":
			selectFields = append(selectFields, f)
		case "atta_type":
			selectFields = append(selectFields, f)
		case "atta_path":
			selectFields = append(selectFields, f)
		case "created_at":
			selectFields = append(selectFields, f)
		}
	}

	var createScanVar = func(fields []query.Expr) (*Attachment, []interface{}) {
		var attachmentVar Attachment
		scanFields := make([]interface{}, 0)

		for _, f := range fields {
			switch strcase.ToSnake(f.Value) {

			case "id":
				scanFields = append(scanFields, &attachmentVar.Id)
			case "share_id":
				scanFields = append(scanFields, &attachmentVar.ShareId)
			case "name":
				scanFields = append(scanFields, &attachmentVar.Name)
			case "atta_type":
				scanFields = append(scanFields, &attachmentVar.AttaType)
			case "atta_path":
				scanFields = append(scanFields, &attachmentVar.AttaPath)
			case "created_at":
				scanFields = append(scanFields, &attachmentVar.CreatedAt)
			}
		}

		return &attachmentVar, scanFields
	}

	sqlStr, params := b.Fields(selectFields...).ResolveQuery()

	rows, err := m.db.QueryContext(context.Background(), sqlStr, params...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	attachments := make([]Attachment, 0)
	for rows.Next() {
		attachmentReal, scanFields := createScanVar(fields)
		if err := rows.Scan(scanFields...); err != nil {
			return nil, err
		}

		attachmentReal.original = &attachmentOriginal{}
		_ = coll.CopyProperties(attachmentReal, attachmentReal.original)

		attachmentReal.SetModel(m)
		attachments = append(attachments, *attachmentReal)
	}

	return attachments, nil
}

// First return first result for given query
func (m *AttachmentModel) First(builders ...query.SQLBuilder) (Attachment, error) {
	res, err := m.Get(append(builders, query.Builder().Limit(1))...)
	if err != nil {
		return Attachment{}, err
	}

	if len(res) == 0 {
		return Attachment{}, query.ErrNoResult
	}

	return res[0], nil
}

// Create save a new attachment to database
func (m *AttachmentModel) Create(kv query.KV) (int64, error) {

	if _, ok := kv["created_at"]; !ok {
		kv["created_at"] = time.Now()
	}

	sqlStr, params := m.query.Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

// SaveAll save all attachments to database
func (m *AttachmentModel) SaveAll(attachments []Attachment) ([]int64, error) {
	ids := make([]int64, 0)
	for _, attachment := range attachments {
		id, err := m.Save(attachment)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

// Save save a attachment to database
func (m *AttachmentModel) Save(attachment Attachment, onlyFields ...string) (int64, error) {
	return m.Create(attachment.StaledKV(onlyFields...))
}

// SaveOrUpdate save a new attachment or update it when it has a id > 0
func (m *AttachmentModel) SaveOrUpdate(attachment Attachment, onlyFields ...string) (id int64, updated bool, err error) {
	if attachment.Id.Int64 > 0 {
		_, _err := m.UpdateById(attachment.Id.Int64, attachment, onlyFields...)
		return attachment.Id.Int64, true, _err
	}

	_id, _err := m.Save(attachment, onlyFields...)
	return _id, false, _err
}

// UpdateFields update kv for a given query
func (m *AttachmentModel) UpdateFields(kv query.KV, builders ...query.SQLBuilder) (int64, error) {
	if len(kv) == 0 {
		return 0, nil
	}

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).
		Table(m.tableName).
		ResolveUpdate(kv)

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// Update update a model for given query
func (m *AttachmentModel) Update(attachment Attachment, builders ...query.SQLBuilder) (int64, error) {
	return m.UpdateFields(attachment.StaledKV(), builders...)
}

// UpdatePart update a model for given query
func (m *AttachmentModel) UpdatePart(attachment Attachment, onlyFields ...string) (int64, error) {
	return m.UpdateFields(attachment.StaledKV(onlyFields...))
}

// UpdateById update a model by id
func (m *AttachmentModel) UpdateById(id int64, attachment Attachment, onlyFields ...string) (int64, error) {
	return m.Condition(query.Builder().Where("id", "=", id)).UpdateFields(attachment.StaledKV(onlyFields...))
}

// Delete remove a model
func (m *AttachmentModel) Delete(builders ...query.SQLBuilder) (int64, error) {

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).Table(m.tableName).ResolveDelete()

	res, err := m.db.ExecContext(context.Background(), sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()

}

// DeleteById remove a model by id
func (m *AttachmentModel) DeleteById(id int64) (int64, error) {
	return m.Condition(query.Builder().Where("id", "=", id)).Delete()
}
